import { useEffect, useRef } from 'react';
import { Clock, Mesh, OrthographicCamera, PlaneGeometry, Scene, ShaderMaterial, Vector2, Vector3, WebGLRenderer } from 'three';
import './FloatingLines.css';

const vertexShader = `void main(){gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`;
const fragmentShader = `precision highp float;uniform float iTime;uniform vec3 iResolution;uniform float animationSpeed;uniform bool enableTop;uniform bool enableMiddle;uniform bool enableBottom;uniform int topLineCount;uniform int middleLineCount;uniform int bottomLineCount;uniform float topLineDistance;uniform float middleLineDistance;uniform float bottomLineDistance;uniform vec3 topWavePosition;uniform vec3 middleWavePosition;uniform vec3 bottomWavePosition;uniform vec2 iMouse;uniform bool interactive;uniform float bendRadius;uniform float bendStrength;uniform float bendInfluence;uniform bool parallax;uniform float parallaxStrength;uniform vec2 parallaxOffset;uniform vec3 lineGradient[8];uniform int lineGradientCount;const vec3 BLACK=vec3(0.0);const vec3 PINK=vec3(233.0,71.0,245.0)/255.0;const vec3 BLUE=vec3(47.0,75.0,162.0)/255.0;mat2 rot(float r){return mat2(cos(r),sin(r),-sin(r),cos(r));}
vec3 bg(vec2 uv){vec3 c=vec3(0.0);float y=sin(uv.x-0.2)*0.3-0.1;float m=uv.y-y;c+=mix(BLUE,BLACK,smoothstep(0.0,1.0,abs(m)));c+=mix(PINK,BLACK,smoothstep(0.0,1.0,abs(m-0.8)));return c*0.5;}
vec3 getLineColor(float t,vec3 bc){if(lineGradientCount<=0)return bc;if(lineGradientCount==1)return lineGradient[0];float ct=clamp(t,0.0,0.9999)*float(lineGradientCount-1);int i=int(floor(ct));float f=fract(ct);int i2=min(i+1,lineGradientCount-1);return mix(lineGradient[i],lineGradient[i2],f)*0.5;}
float wave(vec2 uv,float off,vec2 scUv,vec2 muV,bool sb){float t=iTime*animationSpeed;float xo=off;float xm=t*0.1;float amp=sin(off+t*0.2)*0.3;float y=sin(uv.x+xo+xm)*amp;if(sb){vec2 d=scUv-muV;float inf=exp(-dot(d,d)*bendRadius);float bo=(muV.y-scUv.y)*inf*bendStrength*bendInfluence;y+=bo;}float m=uv.y-y;return 0.0175/max(abs(m)+0.01,1e-3)+0.01;}
void mainImage(out vec4 fc,in vec2 fcrd){vec2 uv=(2.0*fcrd-iResolution.xy)/iResolution.y;uv.y*=-1.0;if(parallax)uv+=parallaxOffset;vec3 c=vec3(0.0);vec3 b=lineGradientCount>0?vec3(0.0):bg(uv);vec2 muV=vec2(0.0);if(interactive){muV=(2.0*iMouse-iResolution.xy)/iResolution.y;muV.y*=-1.0;}
if(enableBottom){for(int i=0;i<8;i++){if(i>=bottomLineCount)break;float fi=float(i);float t=fi/max(float(bottomLineCount-1),1.0);vec3 lc=getLineColor(t,b);float ang=bottomWavePosition.z*log(length(uv)+1.0);vec2 ruv=uv*rot(ang);c+=lc*wave(ruv+vec2(bottomLineDistance*fi+bottomWavePosition.x,bottomWavePosition.y),1.5+0.2*fi,uv,muV,interactive)*0.2;}}
if(enableMiddle){for(int i=0;i<8;i++){if(i>=middleLineCount)break;float fi=float(i);float t=fi/max(float(middleLineCount-1),1.0);vec3 lc=getLineColor(t,b);float ang=middleWavePosition.z*log(length(uv)+1.0);vec2 ruv=uv*rot(ang);c+=lc*wave(ruv+vec2(middleLineDistance*fi+middleWavePosition.x,middleWavePosition.y),2.0+0.15*fi,uv,muV,interactive);}}
if(enableTop){for(int i=0;i<8;i++){if(i>=topLineCount)break;float fi=float(i);float t=fi/max(float(topLineCount-1),1.0);vec3 lc=getLineColor(t,b);float ang=topWavePosition.z*log(length(uv)+1.0);vec2 ruv=uv*rot(ang);ruv.x*=-1.0;c+=lc*wave(ruv+vec2(topLineDistance*fi+topWavePosition.x,topWavePosition.y),1.0+0.2*fi,uv,muV,interactive)*0.1;}}
fc=vec4(c,1.0);}void main(){vec4 c;mainImage(c,gl_FragCoord.xy);gl_FragColor=c;}`;

const MAX_GRADIENT_STOPS=8;
/* ponytail: kept LOCAL copy instead of src/lib/color-utils.js (HLP-002) because this
   hexToVec3 returns a THREE.Vector3 and supports 3-digit shorthand — the shared
   helper returns a plain array and only handles 6-digit hex. */
function hexToVec3(hex){let v=hex.trim();if(v.startsWith('#'))v=v.slice(1);let r=255,g=255,b=255;if(v.length===3){r=parseInt(v[0]+v[0],16);g=parseInt(v[1]+v[1],16);b=parseInt(v[2]+v[2],16);}else if(v.length===6){r=parseInt(v.slice(0,2),16);g=parseInt(v.slice(2,4),16);b=parseInt(v.slice(4,6),16);}return new Vector3(r/255,g/255,b/255);}

export function FloatingLines({linesGradient,enabledWaves=['top','middle','bottom'],lineCount=[6],lineDistance=[5],topWavePosition,middleWavePosition,bottomWavePosition={x:2.0,y:-0.7,rotate:-1},animationSpeed=1,interactive=true,bendRadius=5,bendStrength=-0.5,mouseDamping=0.05,parallax=true,parallaxStrength=0.2,mixBlendMode='screen',className=''}){
  const containerRef=useRef(null),tgtM=useRef(new Vector2(-1000,-1000)),curM=useRef(new Vector2(-1000,-1000)),tgtI=useRef(0),curI=useRef(0),tgtP=useRef(new Vector2(0,0)),curP=useRef(new Vector2(0,0));
  useEffect(()=>{
    const container=containerRef.current;if(!container)return;let active=true;const scene=new Scene();const camera=new OrthographicCamera(-1,1,1,-1,0,1);camera.position.z=1;
    const renderer=new WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.domElement.style.width='100%';renderer.domElement.style.height='100%';container.appendChild(renderer.domElement);
    const uniforms={iTime:{value:0},iResolution:{value:new Vector3(1,1,1)},animationSpeed:{value:animationSpeed},enableTop:{value:enabledWaves.includes('top')},enableMiddle:{value:enabledWaves.includes('middle')},enableBottom:{value:enabledWaves.includes('bottom')},topLineCount:{value:enabledWaves.includes('top')?lineCount[0]||6:0},middleLineCount:{value:enabledWaves.includes('middle')?lineCount[1]||6:0},bottomLineCount:{value:enabledWaves.includes('bottom')?lineCount[2]||6:0},topLineDistance:{value:(typeof lineDistance==='number'?lineDistance:lineDistance[0]||0.1)*0.01},middleLineDistance:{value:(typeof lineDistance==='number'?lineDistance:lineDistance[1]||0.1)*0.01},bottomLineDistance:{value:(typeof lineDistance==='number'?lineDistance:lineDistance[2]||0.1)*0.01},topWavePosition:{value:new Vector3(topWavePosition?.x??10,topWavePosition?.y??0.5,topWavePosition?.rotate??-0.4)},middleWavePosition:{value:new Vector3(middleWavePosition?.x??5,middleWavePosition?.y??0,middleWavePosition?.rotate??0.2)},bottomWavePosition:{value:new Vector3(bottomWavePosition?.x??2,bottomWavePosition?.y??-0.7,bottomWavePosition?.rotate??0.4)},iMouse:{value:new Vector2(-1000,-1000)},interactive:{value:interactive},bendRadius:{value:bendRadius},bendStrength:{value:bendStrength},bendInfluence:{value:0},parallax:{value:parallax},parallaxStrength:{value:parallaxStrength},parallaxOffset:{value:new Vector2(0,0)},lineGradient:{value:Array.from({length:MAX_GRADIENT_STOPS},()=>new Vector3(1,1,1))},lineGradientCount:{value:0}};
    if(linesGradient&&linesGradient.length>0){uniforms.lineGradientCount.value=linesGradient.length;linesGradient.slice(0,MAX_GRADIENT_STOPS).forEach((h,i)=>{const c=hexToVec3(h);uniforms.lineGradient.value[i].set(c.x,c.y,c.z);});}
    const material=new ShaderMaterial({uniforms,vertexShader,fragmentShader});const geometry=new PlaneGeometry(2,2);const mesh=new Mesh(geometry,material);scene.add(mesh);const clock=new Clock();
    const setSize=()=>{const el=containerRef.current;renderer.setSize(el.clientWidth,el.clientHeight,false);uniforms.iResolution.value.set(renderer.domElement.width,renderer.domElement.height,1);};setSize();
    const ro=new ResizeObserver(()=>{if(active)setSize();});ro.observe(container);
    const onMove=(e)=>{const rect=renderer.domElement.getBoundingClientRect();const x=e.clientX-rect.left,y=e.clientY-rect.top;const dpr=renderer.getPixelRatio();tgtM.current.set(x*dpr,(rect.height-y)*dpr);tgtI.current=1;if(parallax){const cx=rect.width/2,cy=rect.height/2;tgtP.current.set((x-cx)/rect.width*parallaxStrength,-(y-cy)/rect.height*parallaxStrength);}};
    const onLeave=()=>{tgtI.current=0;};if(interactive){renderer.domElement.addEventListener('pointermove',onMove);renderer.domElement.addEventListener('pointerleave',onLeave);}
    let raf=0;const loop=()=>{if(!active)return;uniforms.iTime.value=clock.getElapsedTime();if(interactive){curM.current.lerp(tgtM.current,mouseDamping);uniforms.iMouse.value.copy(curM.current);curI.current+=(tgtI.current-curI.current)*mouseDamping;uniforms.bendInfluence.value=curI.current;}if(parallax){curP.current.lerp(tgtP.current,mouseDamping);uniforms.parallaxOffset.value.copy(curP.current);}renderer.render(scene,camera);raf=requestAnimationFrame(loop);};loop();
    return()=>{active=false;cancelAnimationFrame(raf);ro.disconnect();if(interactive){renderer.domElement.removeEventListener('pointermove',onMove);renderer.domElement.removeEventListener('pointerleave',onLeave);}geometry.dispose();material.dispose();renderer.dispose();renderer.forceContextLoss();if(renderer.domElement.parentElement)renderer.domElement.parentElement.removeChild(renderer.domElement);};
  },[linesGradient,enabledWaves,lineCount,lineDistance,topWavePosition,middleWavePosition,bottomWavePosition,animationSpeed,interactive,bendRadius,bendStrength,mouseDamping,parallax,parallaxStrength]);
  return <div ref={containerRef} className={'floating-lines-container'+(className?' '+className:'')} style={{mixBlendMode}} />;
}
